spring.application.name=demo

# Exposer l'endpoint Prometheus et les endpoints de santé
management.endpoints.web.exposure.include=health,prometheus

# Activer la gestion native des sondes Liveness/Readiness pour Kubernetes
management.health.probes.enabled=true

# (Optionnel) Afficher les détails du health check
management.endpoint.health.show-details=always

