spring.application.name=demo

# Endpoints Actuator & Prometheus
management.endpoints.web.exposure.include=health,prometheus
management.health.probes.enabled=true
management.endpoint.health.show-details=always

# URL Cible
app.target-url=${TARGET_URL:http://localhost:8080/recursive}

# FORMAT DE LOG JSON
logging.structured.format.console=ecs

# ACTIVER EXPLICITEMENT LE TRACING WEB
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# FORCER LA CORRÉLATION MDC (Crucial)
management.tracing.baggage.correlation.enabled=true

# S'assurer que Spring MVC enregistre les observations HTTP
management.observations.http.server.requests.name=http.server.requests

# Nom du service Helm : release-name (zipkin) + namespace (monitoring)
management.tracing.export.zipkin.endpoint=http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans
management.tracing.export.zipkin.enabled=true

# Forcer les logs de debug sur le tracing et l'exportateur Zipkin
logging.level.io.micrometer.tracing=DEBUG
logging.level.org.springframework.cloud.zipkin=DEBUG
logging.level.zipkin2=DEBUG
logging.level.org.springframework.boot.autoconfigure.zipkin=DEBUG
logging.level.io.micrometer.tracing.exporter.zipkin=DEBUG
